pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('test JDK') {
           def javaHome = tool 'jdk8';
        withEnv(["JAVA_HOME=${javaHome}"]) {
            sh "java -version"
        }
        }  
    }
}
