pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        },
        stage('test JDK') {
            steps {
                sh "java -version"
            }
        }  
    }
}
