import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

node {
    def jobNameSegs = env.JOB_NAME.split('/')
    def appName
    if (jobNameSegs.length == 1) {
      appName = jobNameSegs[0]
    } else {
      appName = jobNameSegs[jobNameSegs.length - 2]
    }
    def appProfile = env.BRANCH_NAME == "main" ? "live" : "trunk"
    def time = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))
    def dockerImage = "docker.kelvin.cn/kelvin/${appName}:${env.BRANCH_NAME}-${time}"

    stage('Hello') {
        echo 'Hello World'
    }

    stage('Test JDK') {
        def javaHome = tool 'jdk8'  // 获取 JDK8 的路径
        echo "JAVA_HOME: ${javaHome}"  // 输出 javaHome 变量的值
        withEnv([
                "JAVA_HOME=${javaHome}",
                "PATH=${javaHome}/bin:${env.PATH}"
        ]) {
            sh "java -version"
        }
    }

    stage('Maven Build') {
        def javaHome = tool 'jdk8'
        withEnv([
                "JAVA_HOME=${javaHome}",
                "PATH=${javaHome}/bin:${env.PATH}"
        ]) {
            sh "java -version"
            sh 'mvn clean install'
        }
    }

    stage('Docker Build') {
        def dockerfile = "dockerfile/Dockerfile"
        sh "docker build -t ${dockerImage} -f ${dockerfile} ."
    }

    
}
